Add support for FTP uploads
Since `kdump-config` will use busybox's ftpput, let kdump-tools depend
on busybox.

Closes: #856957
Signed-off-by: Benjamin Drung <benjamin.drung@cloud.ionos.com>
Signed-off-by: Benjamin Drung <bdrung@debian.org>

diff --git a/debian/kdump-config.in b/debian/kdump-config.in
--- a/debian/kdump-config.in
+++ b/debian/kdump-config.in
@@ -135,8 +135,20 @@ function kdump_show()
 		echo "NFS_TIMEO:        ${NFS_TIMEO:=600}"
 		echo "NFS_RETRANS       ${NFS_RETRANS:=3}"
 	fi
+	if [ -n "$FTP" ]; then
+		echo "FTP:              $FTP"
+		if [ -n "$FTP_USER" ]; then
+			echo "FTP_USER:         $FTP_USER"
+		fi
+		if [ -n "$FTP_PASSWORD" ]; then
+			echo "FTP_PASSWORD:     is set"
+		fi
+		if [ -n "$FTP_PORT" ]; then
+			echo "FTP_PORT:         $FTP_PORT"
+		fi
+	fi
 
-	if [ -n "$SSH" ] || [ -n "$NFS" ]; then
+	if [ -n "$SSH" ] || [ -n "$NFS" ] || [ -n "$FTP" ]; then
 		HOSTTAG="${HOSTTAG:=ip}"
 		echo "HOSTTAG:          $HOSTTAG"
 	fi
@@ -589,7 +601,7 @@ function define_stampdir()
 	STAMP=$1
 	HOSTTAG="${HOSTTAG:=ip}"
 
-	if [ -z "$SSH" ] && [ -z "$NFS" ]; then
+	if [ -z "$SSH" ] && [ -z "$NFS" ] && [ -z "$FTP" ]; then
 		echo "$KDUMP_COREDIR/$STAMP"
 	elif [ "$HOSTTAG" = "hostname" ];then
 		echo "$KDUMP_COREDIR/$(hostname)-$STAMP"
@@ -750,6 +762,77 @@ function kdump_save_core()
 		if [ $UMNT_ERROR -ne 0 ] ; then
 			log_failure_msg "$NAME: Unable to cleanly unmount the NFS file system"
 			logger -t $NAME "Unable to cleanly unmount the NFS file system"
+		fi
+	fi
+
+	return $ERROR
+}
+
+kdump_save_core_to_ftp()
+{
+	KDUMP_REMOTE_HOST="${FTP%%:*}"
+	KDUMP_COREDIR="${FTP#*:}"
+	if [ "$KDUMP_COREDIR" = "$FTP" ]; then
+		# No colon in FTP specified. Use / as path
+		KDUMP_COREDIR="/"
+	fi
+
+	KDUMP_STAMP=$(date +"%Y%m%d%H%M")
+	KDUMP_STAMPDIR=$(define_stampdir "")
+
+	KDUMP_COREFILE="${KDUMP_STAMPDIR}dump.$KDUMP_STAMP"
+	KDUMP_TMPDMESG="/tmp/dmesg.$KDUMP_STAMP"
+	KDUMP_DMESGFILE="${KDUMP_STAMPDIR}dmesg.$KDUMP_STAMP"
+	ERROR=0
+
+	FTPPUT_ARGS=""
+	if [ -n "$FTP_USER" ]; then
+		FTPPUT_ARGS="$FTPPUT_ARGS -u $FTP_USER"
+	fi
+	if [ -n "$FTP_PASSWORD" ]; then
+		FTPPUT_ARGS="$FTPPUT_ARGS -p $FTP_PASSWORD"
+	fi
+	if [ -n "$FTP_PORT" ]; then
+		FTPPUT_ARGS="$FTPPUT_ARGS -P $FTP_PORT"
+	fi
+
+	# Add '-F' [flatten] to MAKEDUMP_ARGS, if not there:
+	[ "${MAKEDUMP_ARGS#-F*}" != "${MAKEDUMP_ARGS}" ] || MAKEDUMP_ARGS="${MAKEDUMP_ARGS} -F"
+	log_action_msg "sending makedumpfile $MAKEDUMP_ARGS $vmcore_file via FTP to $KDUMP_REMOTE_HOST:$KDUMP_COREFILE"
+	# shellcheck disable=SC2086
+	makedumpfile $MAKEDUMP_ARGS $vmcore_file | busybox ftpput $FTPPUT_ARGS "$KDUMP_REMOTE_HOST" "$KDUMP_COREFILE" -
+	ERROR=$?
+
+	# did we succeed?
+	if [ $ERROR -ne 0 ]; then
+		log_failure_msg "$NAME: failed to save vmcore via FTP in $KDUMP_REMOTE_HOST:$KDUMP_COREFILE"
+		logger -t $NAME "failed to save vmcore via FTP in $KDUMP_REMOTE_HOST:$KDUMP_COREFILE"
+	else
+		log_success_msg "$NAME: saved vmcore via FTP in $KDUMP_REMOTE_HOST:$KDUMP_COREFILE"
+		logger -t $NAME "saved vmcore via FTP in $KDUMP_REMOTE_HOST:$KDUMP_COREFILE"
+	fi
+
+	# dump the dmesg buffer
+	if [ "$KDUMP_DUMP_DMESG" -eq 1 ] ; then
+		log_action_msg "running makedumpfile --dump-dmesg $vmcore_file $KDUMP_TMPDMESG"
+		makedumpfile --dump-dmesg $vmcore_file "$KDUMP_TMPDMESG"
+		ERROR=$?
+		if [ $ERROR -ne 0 ] ; then
+			log_failure_msg "$NAME: makedumpfile --dump-dmesg failed. dmesg content will be unavailable"
+			logger -t $NAME "makedumpfile --dump-dmesg failed. dmesg content will be unavailable"
+		else
+			# shellcheck disable=SC2086
+			busybox ftpput $FTPPUT_ARGS "$KDUMP_REMOTE_HOST" "$KDUMP_DMESGFILE" "$KDUMP_TMPDMESG"
+			ERROR=$?
+		fi
+
+		# did we succeed?
+		if [ $ERROR -eq 0 ]; then
+			log_success_msg "$NAME: saved dmesg content via FTP in $KDUMP_REMOTE_HOST:$KDUMP_DMESGFILE"
+			logger -t $NAME "saved dmesg content via FTP in $KDUMP_REMOTE_HOST:$KDUMP_DMESGFILE"
+		else
+			log_failure_msg "$NAME: failed to save dmesg content via FTP in $KDUMP_REMOTE_HOST:$KDUMP_DMESGFILE"
+			logger -t $NAME "failed to save dmesg content via FTP in $KDUMP_REMOTE_HOST:$KDUMP_DMESGFILE"
 		fi
 	fi
 
@@ -997,10 +1080,13 @@ case "$1" in
 	exit 0;
 	;;
   savecore)
+	if [ -n "$FTP" ]; then
+		kdump_save_core_to_ftp
+	fi
 	if [ -n "$SSH" ];then
 		kdump_save_core_to_ssh
 	fi
-	if [ -n "$NFS" ] || [ -z "$SSH" ]; then
+	if [ -n "$NFS" ] || [ -z "${FTP}${SSH}" ]; then
 		kdump_save_core
 	fi
 	exit $?
